---
abstract: 'Code coverage metrics for your distribution'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100991'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-App-Command-cover
provides:
  Dist::Zilla::App::Command::cover:
    file: lib/Dist/Zilla/App/Command/cover.pm
    version: 1.101000
recommends: {}
requires:
  Devel::Cover: 0
  Dist::Zilla::App: 0
  File::Temp: 0
  File::chdir: 0
  Path::Class: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-App-Command-cover
  homepage: http://search.cpan.org/dist/Dist-Zilla-App-Command-cover/
  repository: http://github.com/hanekomu/Dist-Zilla-App-Command-cover
version: 1.101000
